### ISSUE TITLE
500 - Error - Perl execution failed

### ISSUE THREAD

**Issue by kibeb** [Burnett01/webmin-notes#1]
I've installed webmin-notes 0.2 via Webmin Configuration module, now it sits in the Webmin menu (v.1.920, Authentic theme v.19.36, Debian 9), but after clicking it I only get:

> 500 - Error - Perl execution failed
> Can't locate webmin-notes-lib.pl in @INC (@INC contains: /usr/share/webmin /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/webmin/webmin-notes/index.cgi line 2.

Please advise. TIA.

**Comment by Burnett01** [comment]
@kibeb  Hello, sorry for the late response. Github did not notify me about your issue report.
Regarding your report, it looks like Webmin is unable to find the module. We last used this module in 2015 and 2016 so there may have been crucial changes to Webmin modules. 

Can you please tell me what Webmin version you're on? 
I can then take a closer look and test this module on a system similiar to yours (Debian 9, Authentic theme).

Thank you in advance, Greetings - Steve.

**Comment by kibeb** [comment]
@Burnett01 Hi, at the time of the report I was on Webmin version 1.920 (it's included in my issue report BTW), now I'm on version 1.930 and the problem is still the same. Thank you.

**Comment by Burnett01** [comment]
Hello @kibeb, it has been a long time but finally I was able to test this module with Webmin 1.979 and the latest version of the authentic-theme (19.82). Rather than adding the code-snippet to the index.cgi oder body.cgi, you will have to add it to the sysinfo.cgi of the theme.
This is because each theme has its own way of defining its entrypoint (index).

I've added an example to the Readme of this repository, where you can see how you can include the snippet.

Greetings, Steve
